version: '3.8'
services:
  postgres-test:
    image: postgres:15
    command: postgres -c 'max_connections=2048'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: benchmark
    ports:
      - "5432:5432"
